name: cp-vton-1
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py38_0
  - cloudpickle=1.5.0=py_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py38_0
  - cytoolz=0.10.1=py38h7b6447c_0
  - dask-core=2.20.0=py_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.9=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.65.0=h3eb4bd4_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - imageio=2.9.0=py_0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.3=py38h5ca1d4c_0
  - ipython=7.16.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.17.1=py38_0
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=6.1.6=py_0
  - jupyter_core=4.6.3=py38_0
  - kiwisolver=1.2.0=py38hfd86e86_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.3=h8b12597_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py38hef1b27d_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.1.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - ninja=1.9.0=py38hfd86e86_0
  - numpy=1.18.5=py38ha1c710e_0
  - numpy-base=1.18.5=py38hde5b4d6_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h7b6447c_0
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.2.0=py38hb39fc2d_0
  - pip=20.1.1=py38_1
  - prompt-toolkit=3.0.5=py_0
  - protobuf=3.12.3=py38h950e882_0
  - ptyprocess=0.6.0=py38_0
  - pygments=2.6.1=py_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.3=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.5.1=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pywavelets=1.1.1=py38h7b6447c_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - pyzmq=19.0.1=py38he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - scikit-image=0.16.2=py38h0573a6f_0
  - scipy=1.5.0=py38h0b6359f_0
  - setuptools=49.2.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - tensorboardx=2.1=py_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.6.1=py38_cu101
  - tornado=6.0.4=py38h7b6447c_1
  - tqdm=4.47.0=py_0
  - traitlets=4.3.3=py38_0
  - wcwidth=0.2.5=py_0
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.2=he6710b0_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h0b5b093_0
  - pip:
    - overrides==3.1.0
